matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install -r CSE_backend/requirements.txt
      before_script:
        - cd CSE_backend
        - python manage.py runserver &
      script:
        - python backend_test.py
